"""6

Revision ID: 39005256da2c
Revises: 405724327192
Create Date: 2020-07-01 13:41:04.372221

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '39005256da2c'
down_revision = '405724327192'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('stores', sa.Column('account_id', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('stores', 'account_id')
    # ### end Alembic commands ###
