"""5

Revision ID: 405724327192
Revises: 4b2af9c105d8
Create Date: 2020-06-30 23:25:33.687035

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '405724327192'
down_revision = '4b2af9c105d8'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###

    op.alter_column('receipts', 'title',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('receipts', 'total_payment',
                    existing_type=sa.Float(),
                    nullable=False)
        # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('receipts', 'title',
               existing_type=sa.VARCHAR(),
               nullable=False)
    # ### end Alembic commands ###
