"""7

Revision ID: 52f83f7af047
Revises: 39005256da2c
Create Date: 2020-07-02 02:14:41.179666

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '52f83f7af047'
down_revision = '39005256da2c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###

    op.add_column('receipts', sa.Column('hst', sa.Float(), nullable=True))
    op.add_column('receipts', sa.Column('subtotal', sa.Float(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###

    op.drop_column('receipts', 'subtotal')
    op.drop_column('receipts', 'hst')
    # ### end Alembic commands ###
