"""2

Revision ID: 643ddca41c37
Revises: b818381858cf
Create Date: 2020-06-30 17:30:48.314467

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '643ddca41c37'
down_revision = 'b818381858cf'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('persons', 'current_book_id')
    op.drop_column('persons', 'is_legal')
    op.drop_column('persons', 'bio')

def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###

    op.add_column('persons', sa.Column('bio', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.add_column('persons', sa.Column('is_legal', sa.BOOLEAN(), autoincrement=False, nullable=True))
    op.add_column('persons', sa.Column('current_book_id', postgresql.UUID(), autoincrement=False, nullable=True))
    # ### end Alembic commands ###
