"""3

Revision ID: 6bcc5e7c46a6
Revises: 643ddca41c37
Create Date: 2020-06-30 17:38:51.259055

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6bcc5e7c46a6'
down_revision = '643ddca41c37'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('fk_tb_receipts_col_payer_id', 'receipts', type_='foreignkey')
    op.drop_constraint('fk_tb_receipts_col_payee_id', 'receipts', type_='foreignkey')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_foreign_key('fk_tb_receipts_col_payee_id', 'receipts', 'stores', ['payee_id'], ['id'])
    op.create_foreign_key('fk_tb_receipts_col_payer_id', 'receipts', 'persons', ['payer_id'], ['id'])

    # ### end Alembic commands ###
